chore(ci): move from npm to pnpm

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,7 +8,7 @@ jobs:
     if: "!contains(github.event.head_commit.message, 'skip release') && !contains(github.event.head_commit.message, 'skip ci')"
     steps:
     - name: Checkout code
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
       with:
         fetch-depth: 0
 
@@ -17,31 +17,36 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_PERSONAL_TOKEN }}
 
+    - name: setup pnpm
+      uses: pnpm/action-setup@v2
+      with:
+        version: 8
+
     - name: Set up Node.js
-      uses: actions/setup-node@v3
+      uses: actions/setup-node@v4
       with:
         node-version: 'lts/*'
-        cache: 'npm'
+        cache: 'pnpm'
         registry-url: 'https://registry.npmjs.org'
 
     - name: Install dependencies
-      run: npm ci
+      run: pnpm install
 
     - name: Check lock file for untrusted packages
-      run: npm_config_yes=true npx lockfile-lint --path package-lock.json --allowed-hosts npm --validate-https
+      run: pnpm dlx lockfile-lint --path package-lock.json --allowed-hosts npm --validate-https
 
     - name: Generate OpenAPI bindings and build package
       run: |
-        npm run generate
-        npm run build
+        pnpm run generate
+        pnpm run build
 
     - name: Check package for packaging errors
-      run: npm_config_yes=true npx publint run
+      run: pnpm dlx publint run
 
     - name: Check for uncommitted changes
       # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
       run: |
         git diff --exit-code --stat -- . ':!node_modules' ':!dist' \
-        || (echo "##[error] found changed files after build. please 'npm run generate && npm run build'" \
+        || (echo "##[error] found changed files after build. please 'pnpm run generate && pnpm run build'" \
                  "and commit all changes" \
             && exit 1)
